Simplifying Our Project - First video with Sam leading - Big restructure of all content, moving and deleting stuff within UE and Finder - UE still runs after all this moving around, but with a warning error:
Default Property warnings and errors:
Error: CDO Constructor (TestingGroundsGameMode): Failed to find /Game/FirstPersonCPP/Blueprints/FirstPersonCharacter.FirstPersonCharacter_C

Error: CDO Constructor (TestingGroundsHUD): Failed to find /Game/FirstPerson/Textures/FirstPersonCrosshair

Error: CDO Constructor (TP_ThirdPersonGameMode): Failed to find /Game/ThirdPersonCPP/Blueprints/ThirdPersonCharacter.ThirdPersonCharacter_C

- The level doesn’t auto load at present so needs to be selected
- Always crashes when play is attempted